#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#ВОРКСПЕЙСЫ
bspc monitor -d I II III IV V VI VII VIII IX X

#РАМКИ И ГАПСЫ
bspc config border_width         1
bspc config window_gap          10
bspc config normal_border_color "#ffffff"
bspc config active_border_color "#ffffff"
bspc config focused_border_color "#000000"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНА
bspc config presel_feedback_color "#ffffff"

#ПРАВИЛА ОКОН
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Firefox state=floating rectangle=1350x900+50+90 desktop='^1'

#ЗАПУСК ПРИЛОЖЕНИЙ
picom &

#ОБОИ
feh --bg-scale /home/jester/Pictures/wallpapers.jpg

#СМЕНА РАСКЛАДКИ
setxkbmap -option grp:alt_shift_toggle us,ru &

#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier super